# Nuvens

**Objetivo Geral**: Resolver Equações Diferenciais de Primeira Ordem.

**Objetivo Especifico**: Em Física, as equações diferenciais de primeira ordem interessantes, são exponenciais. Em casos simples, tais problemas se beneficam de métodos numéricos também simples, como  o Método de Euler. Trabalharemos esse método com valores escalares e matriciais.

A manipulação de tais equações de forma analítica também é recorrente, por isso, vamos usar ferramentas simbólicas para servir de *facilitadores* de nossas contas.

Por último, 'veremos' uma equações diferencial em busca de soluções interessantes, normalmente por pontos de equilibrio. Para tal, precisamos criar um *Campos de Direções*, produzidas em por gráfico chamado `quiver`.

**Conteúdo**: Lei de Beer-Lambert; Método de Euler; Matrizes de Mueller; Exponencial de Matriz; Cálculo Simbólico; Equação de Transferência Radiativa; Quiver;


O capítulo anterior mostrou que o espectro de radiação solar não é perfeito devido a efeitos de absorção (de certas frequências) pela atmosfera terrestre. Isso acontece em todo o universo, e ao olhar para as *janelas de frequências* certas, podemos ver o que esta escondido atrás de uma atmosfera ou de uma nuvem. O Telescópio James Webb é um ótimo exemplo, ele foi criado para ter imagens no infra vermelho, justamente pois as nuvens inter estelares tem menor espalhamento nessa região do espectro eletromagnético.

Esse curso de Física Computacional é direcionado a alunos em anos inciais da graduação, logo, não posso apresentar um modelo matemático (de clássica ou quântica avançadas)  para encontrar frequências de ressonâncias, pois só traria frustrações ao leitor. No entanto, podemos aprender alguns conceitos básicos que são correlatos a espalhamento, e cuja matemática não é complexa, são eles **absorção** e **emissão**.


<!-- {{< include _43quiver.qmd >}} -->