## O Experimento

Você pode aumentar ou diminuir a altura do som do seu celular com 2 botões. Contudo, seu ouvido não funciona da mesma maneira. Se você é exposto a sons de mesma intensidade, mas frequências diferentes, você terá a impressão que os sons estão em volumes diferentes. Essa sensibilidade diferente para cada frequência depende de pessoa para pessoa, e sua primeira atividade será descobrir os limites dos **seus** ouvidos.

---

Você irá realizar o experimento proposto em [@p2_experimento], para acessar os seus detalhes, clique [aqui](https://www.sciencebuddies.org/science-fair-projects/project-ideas/HumBio_p011/human-biology-health/measuring-hearing-threshold-different-pitches). A atividade consiste em escutar sons com frequências bem definidas, porém de intensidades diferentes ao longo do tempo. Ao contar a quantidade de tons, você conseguirá calcular os seus limites auditivos.

::: callout-caution
## Aviso
Não esqueça que seu primeiro passo na atividade não é preencher a tabela, mas sim ajustar a altura do fone de ouvido para que você escute 18 ou 19 batidas em 3500Hz.

Leia toda a prática antes de começar a realiza-lá.
:::

::: callout-caution
## Aviso
Não se preocupe com os resultados no regime de alta frequência. Fones de ouvidos não são feitos para ter alta fidelidade nessa região, logo, você provavelmente não escutará tantas batidas.

Relaxe, você não está surdo.
:::

::: callout-tip
## Dica
Esse experimento é longo e será inevitável a fadiga. Isso é um problema para garantir a qualidade dos seus dados, pois você terá muita atenção para contar as batidas no começo da prática, e não terá a mesma disposição e atenção para contar batidas no final do experimento.

Uma maneira de contornar o cansaço físico é não realizar o experimento de forma linear, escute as frequências em ordem aleatória.
:::

::: callout-note
## Exercício 6.1
Leia atentamente a descrição do [experimento](https://www.sciencebuddies.org/science-fair-projects/project-ideas/HumBio_p011/human-biology-health/measuring-hearing-threshold-different-pitches) e preencha uma tabela com a quantidade de batidas que você escutou em cada repetição.

Armazene os seus resultados em uma planilha\footnote{Tipo Microsoft Excel ou similar}.
:::

::: callout-note
## Exercício 6.2
Salve os dados como um arquivo CSV.
:::

::: callout-note
## Exercício 6.3
Leia os dados em Julia com o pacote `DelimitedFiles.jl`, e com o pacote de vizualização de sua escolha, faça um gráfico `semilogx` dos seus resultados.
```{julia}
#| output: true
using DelimitedFiles
data = readdlm("minha_audicao.csv", ','; skipstart=1);

using Plots
xdata = data[:, 1]
ydata = data[:, 8]

plot(xdata, ydata; label="", markershape=:o, xscale=:log10, xlims=(10, 25_000))
plot!(; xticks=([10, 100, 1000, 10000], ["10", "100", "1000", "10000"]))
plot!(; xlabel="Hertz", ylabel="dB", title="Threshold of Hering")
```

O tamanho da fonte da figura deve ser comparável ao texto onde ele estará embutido.
:::


::: {.callout-note collapse="true"}
## Observação
Salvar arquivos em formato `.csv` é conveniente apenas quando o conjunto de dados é pequeno, pois você pode acessar os dados com um editor de texto.

Quando o conjunto de dados é enorme, e você não precisa de uma banco de dados, use arquivos do formato `.hdf5`.
:::