project:
  type: book

book:
  title: "Fiscomp"
  author: "Noel Araujo Moreira"
  date: "8/15/2022"
  chapters:
    - index.qmd
    - Projeto1/projeto1.qmd
    - Projeto2/projeto2.qmd
    # - summary.qmd
    # - intro.qmd
    - references.qmd
  sharing: [facebook]
  search: true
  # cover-image: cover.jpg


bibliography: references.bib
csl: journal-of-computational-physics-x.csl
format:
  html:
    theme:
      light: lumen
    code-fold: true
  pdf:
    documentclass: scrreprt
    keep-tex: true

jupyter: julia-1.8

